#!/bin/sh
exec < /dev/tty
#clear
CURRENT_BRANCH=`git symbolic-ref --short HEAD`

if [ -n "`git branch -a | grep remotes/origin/${CURRENT_BRANCH}`" ]
then
    REMOTE_BRANCH="origin/${CURRENT_BRANCH}"
else
    REMOTE_BRANCH="origin/HEAD"
fi

git log --graph --decorate=full $CURRENT_BRANCH...$REMOTE_BRANCH

echo -n "Is it Okey to push your commit(s)? (y/n): "
read will

if [ "${will}" = "Y" -o "${will}" = "y" ]
then
    exit 0
else
    echo "\033[0;31mPush is not done.\033[0;39m"
    exit 1
fi
